In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.svm import LinearSVC
from sklearn import svm
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.svm import SVC


In [ ]:
df = pd.read_csv('train.csv')
test_df = pd.read_csv('test.csv')

In [ ]:
df.shape

(45000, 16)

In [ ]:
test_df.shape

(13107, 15)

In [ ]:
dt = df
test_dt = test_df

In [ ]:
df['Elo'] = df['Elo'].fillna(df['Elo'].mode()[0])
df['opp_Elo'] = df['opp_Elo'].fillna(df['opp_Elo'].mode()[0])
df['win_equivalent'] = df['win_equivalent'].fillna(df['win_equivalent'].mode()[0])

test_df['Elo'] = test_df['Elo'].fillna(test_df['Elo'].mode()[0])
test_df['opp_Elo'] = test_df['opp_Elo'].fillna(test_df['opp_Elo'].mode()[0])
test_df['win_equivalent'] = test_df['win_equivalent'].fillna(test_df['win_equivalent'].mode()[0])

# df=df.fillna(df.mean())

In [ ]:
lb = LabelEncoder()
df['team_id'] = lb.fit_transform(df['team_id'])
df['opp_team_id'] = lb.fit_transform(df['opp_team_id'])

test_df['team_id'] = lb.fit_transform(test_df['team_id'])
test_df['opp_team_id'] = lb.fit_transform(test_df['opp_team_id'])


In [ ]:
new = df["date"].str.split("/", n = 2, expand = True) 
  
df["date1"]= new[0] 
df["month"]= new[1] 
df["year"]= new[2] 

# Dropping old Name columns 
df = df.drop(['date'], axis=1)




new1 = test_df["date"].str.split("/", n = 2, expand = True) 
  
test_df["date1"]= new1[0] 
test_df["month"]= new1[1] 
test_df["year"]= new1[2] 

# Dropping old Name columns 
test_df = test_df.drop(['date'], axis=1)


In [ ]:
df['playoff'] = lb.fit_transform(df['playoff'])
test_df['playoff'] = lb.fit_transform(test_df['playoff'])

In [ ]:
df['date1'] = df['date1'].astype(int)
df['month'] = df['month'].astype(int)
df['year'] = df['year'].astype(int)
test_df['date1'] = test_df['date1'].astype(int)
test_df['month'] = test_df['month'].astype(int)
test_df['year'] = test_df['year'].astype(int)

In [ ]:
df.head()

Id  game_seq  season_end  season_game_seq  ...  game_result  date1  month  year
0   1     39323        1997                2  ...            1     11      2  1996
1   2     59211        2012               87  ...            0      6     17  2012
2   3     60691        2014               12  ...            0     11     20  2013
3   4     31900        1990               69  ...            0      3     29  1990
4   5     48134        2004               30  ...            0      1      2  2004

[5 rows x 18 columns]

In [ ]:
test_df.head()

Id  game_seq  season_end  ...  date1  month  year
0  45001     50929        2006  ...      2      1  2006
1  45002     62745        2015  ...      3      4  2015
2  45003     53291        2008  ...     12     25  2007
3  45004     24991        1984  ...     12      2  1983
4  45005     18807        1977  ...      3     25  1977

[5 rows x 17 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Id               45000 non-null  int64  
 1   game_seq         45000 non-null  int64  
 2   season_end       45000 non-null  int64  
 3   season_game_seq  45000 non-null  int64  
 4   playoff          45000 non-null  int64  
 5   team_id          45000 non-null  int64  
 6   Elo              45000 non-null  float64
 7   opp_team_id      45000 non-null  int64  
 8   opp_Elo          45000 non-null  float64
 9   win_equivalent   45000 non-null  float64
 10  bet_ratio        45000 non-null  float64
 11  home_crowd       45000 non-null  int64  
 12  opp_crowd        45000 non-null  int64  
 13  total_crowd      45000 non-null  int64  
 14  game_result      45000 non-null  int64  
 15  date1            45000 non-null  int64  
 16  month            45000 non-null  int64  
 17  year        

In [ ]:
test_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13107 entries, 0 to 13106
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Id               13107 non-null  int64  
 1   game_seq         13107 non-null  int64  
 2   season_end       13107 non-null  int64  
 3   season_game_seq  13107 non-null  int64  
 4   playoff          13107 non-null  int64  
 5   team_id          13107 non-null  int64  
 6   Elo              13107 non-null  float64
 7   opp_team_id      13107 non-null  int64  
 8   opp_Elo          13107 non-null  float64
 9   win_equivalent   13107 non-null  float64
 10  bet_ratio        13107 non-null  float64
 11  home_crowd       13107 non-null  int64  
 12  opp_crowd        13107 non-null  int64  
 13  total_crowd      13107 non-null  int64  
 14  date1            13107 non-null  int64  
 15  month            13107 non-null  int64  
 16  year             13107 non-null  int64  
dtypes: float64(4

In [ ]:
df.shape

(45000, 18)

In [ ]:
test_df.shape


(13107, 17)

In [ ]:
df.drop('Id', axis=1, inplace=True)
df.drop('playoff', axis=1, inplace=True)
# df.drop('season_end', axis=1, inplace=True)
df.drop('date1', axis=1, inplace=True)
# df.drop('year', axis=1, inplace=True)
df.drop('team_id', axis=1, inplace=True)
df.drop('opp_team_id', axis=1, inplace=True)
df.drop('season_end', axis=1, inplace=True)
df.drop('year', axis=1, inplace=True)


test_df.drop('Id', axis=1, inplace=True)
test_df.drop('playoff', axis=1, inplace=True)
# test_df.drop('season_end', axis=1, inplace=True)
test_df.drop('date1', axis=1, inplace=True)
# test_df.drop('year', axis=1, inplace=True)
test_df.drop('team_id', axis=1, inplace=True)
test_df.drop('opp_team_id', axis=1, inplace=True)
test_df.drop('season_end', axis=1, inplace=True)
test_df.drop('year', axis=1, inplace=True)

In [ ]:
df.shape

(45000, 11)

In [ ]:
test_df.shape

(13107, 10)

In [ ]:
y = df['game_result']
df.drop('game_result', axis=1, inplace=True)
x = df

In [ ]:
x.shape

(45000, 10)

In [ ]:
y.shape

(45000,)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x,y, test_size = 0.1, random_state = 0)

In [ ]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier

randomforest = RandomForestClassifier(n_estimators=600)
randomforest.fit(x_train, y_train)
y_pred = randomforest.predict(x_val)
acc_randomforest = round(accuracy_score(y_pred, y_val) * 100, 2)
print(acc_randomforest)

76.98


In [ ]:
from sklearn import metrics

print(metrics.confusion_matrix(y_val, y_pred))

[[2435  340]
 [ 696 1029]]


In [ ]:
# importances = randomforest.feature_importances_
print(randomforest.feature_importances_)

[0.09876209 0.07541428 0.1318544  0.09983012 0.1484929  0.17806093
 0.06738871 0.06691188 0.07037885 0.06290584]


In [ ]:
# Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

gaussian = GaussianNB()
gaussian.fit(x_train, y_train)
y_pred = gaussian.predict(x_val)
acc_gaussian = round(accuracy_score(y_pred, y_val) * 100, 2)
print(acc_gaussian)


66.56


In [ ]:
print(metrics.confusion_matrix(y_val, y_pred))

[[2258  517]
 [ 988  737]]


In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()
logreg.fit(x_train, y_train)
y_pred = logreg.predict(x_val)
acc_logreg = round(accuracy_score(y_pred, y_val) * 100, 2)
print(acc_logreg)

65.47


In [ ]:
print(metrics.confusion_matrix(y_val, y_pred))

[[2358  417]
 [1137  588]]


In [ ]:
# Support Vector Machines
from sklearn.svm import SVC

svc = SVC()
svc.fit(x_train, y_train)
y_pred = svc.predict(x_val)
acc_svc = round(accuracy_score(y_pred, y_val) * 100, 2)
print(acc_svc)

61.67


In [ ]:
print(metrics.confusion_matrix(y_val, y_pred))

[[2775    0]
 [1725    0]]


In [ ]:
# Linear SVC
from sklearn.svm import LinearSVC

linear_svc = LinearSVC()
linear_svc.fit(x_train, y_train)
y_pred = linear_svc.predict(x_val)
acc_linear_svc = round(accuracy_score(y_pred, y_val) * 100, 2)
print(acc_linear_svc)

61.89


/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [ ]:
print(metrics.confusion_matrix(y_val, y_pred))

[[2771    4]
 [1711   14]]


In [ ]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

decisiontree = DecisionTreeClassifier(class_weight=None, max_depth=32,
 max_features=None, max_leaf_nodes=None,
 min_impurity_split=1e-07, min_samples_leaf=5,
 min_samples_split=2, min_weight_fraction_leaf=0.0,
 presort=False, random_state=None)
decisiontree.fit(x_train, y_train)
y_pred = decisiontree.predict(x_val)
acc_decisiontree = round(accuracy_score(y_pred, y_val) * 100, 2)
print(acc_decisiontree)

/usr/local/lib/python3.6/dist-packages/sklearn/tree/_classes.py:301: FutureWarning: The min_impurity_split parameter is deprecated. Its default value will change from 1e-7 to 0 in version 0.23, and it will be removed in 0.25. Use the min_impurity_decrease parameter instead.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/tree/_classes.py:319: FutureWarning: The parameter 'presort' is deprecated and has no effect. It will be removed in v0.24. You can suppress this warning by not passing any value to the 'presort' parameter.
  FutureWarning)


73.31


In [ ]:
print(metrics.confusion_matrix(y_val, y_pred))

[[2230  545]
 [ 656 1069]]


In [ ]:
# Gradient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier

gbk = GradientBoostingClassifier(n_estimators=2000)
gbk.fit(x_train, y_train)
y_pred = gbk.predict(x_val)
acc_gbk = round(accuracy_score(y_pred, y_val) * 100, 2)
print(acc_gbk)

83.62


In [ ]:
print(metrics.confusion_matrix(y_val, y_pred))

[[2519  256]
 [ 481 1244]]


In [ ]:
models = pd.DataFrame({
    'Model': ['Support Vector Machines',  
              'Random Forest', 'Naive Bayes', 'Linear SVC',
              'Decision Tree', 'Gradient Boosting Classifier'],
    'Score': [acc_svc,  
              acc_randomforest, acc_gaussian, acc_linear_svc, acc_decisiontree,
               acc_gbk]})
models.sort_values(by='Score', ascending=False)

Model  Score
5  Gradient Boosting Classifier  83.60
1                 Random Forest  76.98
4                 Decision Tree  72.96
2                   Naive Bayes  66.56
0       Support Vector Machines  61.67
3                    Linear SVC  43.36